indent-width = 2 # Please no 4 indent-length
line-length = 120
target-version = "py312"
preview = true

[lint]

extend-select = [
  "B",        # Bugbear
  "F",        # Pyflakes rules
  "W",        # PyCodeStyle warnings
  "E",        # PyCodeStyle errors
  "I",        # Sort imports properly
  "N",        # Naming style changes
  "UP",       # Warn if certain things can changed due to newer Python versions
  "C4",       # Catch incorrect use of comprehensions, dict, list, etc
  "ISC",      # Good use of string concatenation
  "ICN",      # Use common import conventions
  "RET",      # Good return practices
  "SIM",      # Common simplification rules
  "TID",      # Some good import practices
  "PTH",      # Use pathlib instead of os.path
  "NPY",      # Some numpy-specific things
  "ERA001",   # Commented out code
  # "ANN001",   # Typing Annotations check
  "RUF",
  "FURB",
  "PLR",
]

ignore = [
  'ISC001',
  'C408',
  'B008',
  'B028',
  'N818',
  'RUF009',
  
  'E111',
  'E114',
  'RUF029',
  'PLR0913',
  'PLR0917'

]

exclude = [
  ".pixi",
  "plants_backend/**"
]

fixable = ["ALL"]
unfixable = []

[format]
quote-style = "single"

[lint.flake8-quotes]
docstring-quotes = "double"

[lint.isort]
force-sort-within-sections = true


[lint.per-file-ignores]
"*/test/**/*.py" = ["D", "F"]
"test_*.py" = ["D",  "F"]
"*/geometry_2d.py" = ["E741"]
